Removed run.sh from .dockerignore

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -39,12 +39,19 @@ jobs:
 
     - name: Build local Directory sync service image.
       run: |
-        docker build --no-cache -t samply/directory_sync_service .
+        docker build --no-cache -progress=plain -t samply/directory_sync_service .
+
+    - name: Show files that will be in data loader build context
+      working-directory: ci/data_loader
+      run: |
+        pwd
+        ls -la
+        test -f run.sh && echo "✅ run.sh present" || (echo "❌ run.sh missing" && exit 1)
 
     - name: Build local image that will load data from files to FHIR store (Blaze).
       working-directory: ci/data_loader
       run: |
-        docker build --no-cache -t samply/data_loader .
+        docker build --no-cache -progress=plain -t samply/data_loader .
 
     - name: Run integration stack (docker compose)
       working-directory: ci
